### ISSUE TITLE
Add compiler optimization if using x86 processor

### ISSUE THREAD

**Issue by gocarlos** [OpenMapper/ORB_SLAM2#9]
add this possibility to the cmakelists

**Comment by nidegen** [comment]
see cmake_modules in OpenMapper which configure iOS flags. we could do the same for x86

**Comment by nidegen** [comment]
flags concerned are following that were removed due to incomaptibility to arm:

```
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -w  -O3 -march=native ")
```

**Comment by gocarlos** [comment]
this is done right now with openmapper... closing this issue
